theme: jekyll-theme-cayman
github:
  repository_name: Bodiless Drupal Showcase
  project_tagline: >
    DrupalCon: Baltimore 2017<br>
    Sponsored by <a href="http://www.quotient-inc.com" target="_blank">Quotient, Inc.</a><br>
    Modules and Code<br>
