theme: jekyll-theme-cayman
github:
  repository_name: Bodiless Drupal Showcase
  project_tagline: >
    DrupalCon: Baltimore 2017  
    Sponsored by [Quotient, Inc.](http://www.quotient-inc.com)  
    Modules and Code
